"use strict";
exports.__esModule = true;
var clase_Movie_1 = require("./clase_Movie");
var Clase_Profesional_1 = require("./Clase_Profesional");
var clase_imdb_1 = require("./clase_imdb");
var profesional1 = new Clase_Profesional_1.profesional("tom", 50, "masculino", 65, 170, "castaño", "marron", "economista", "NO", "Americana", 0, "actor");
var profesional2 = new Clase_Profesional_1.profesional("the rock", 53, "masculino", 100, 190, "calvo", "marron", "economista", "NO", "Americana", 0, "actor");
var profesional3 = new Clase_Profesional_1.profesional("Dicaprio", 45, "masculino", 70, 180, "castaño", "azul", "economista", "NO", "Americana", 1, "actor");
var director1 = new Clase_Profesional_1.profesional("Quentin", 60, "masculino", 80, 170, "calvo", "marron", "Director", "NO", "Americana", 0, "director");
var writer1 = new Clase_Profesional_1.profesional("Spielberg", 65, "masculino", 100, 190, "calvo", "marron", "escritor", "NO", "Americana", 0, "escritor");
var Movie1 = new clase_Movie_1.movie("kill Bill3", 2021, "americana", "Quentin");
Movie1.actors = [profesional1, profesional2, profesional3];
Movie1.director = director1;
Movie1.writer = writer1;
Movie1.distributor = "Universal";
Movie1.isMCU = "NO";
Movie1.mainCharacterName = "Tom";
Movie1.language = "Ingles";
Movie1.producer = "fox";
Movie1.plataform = "amazon";
//console.log(Movie1.toprint());
var Movie2 = new clase_Movie_1.movie("Kill Bill4", 2022, "americana", "Quentin");
Movie2.actors = [profesional3, profesional2, profesional1];
Movie2.director = writer1;
Movie2.writer = director1;
Movie2.distributor = "Pixar";
Movie2.isMCU = "Si";
Movie2.mainCharacterName = "Dicaprio";
Movie2.language = "Chino";
Movie2.producer = "Universal";
Movie2.plataform = "netflix";
var imdb1 = new clase_imdb_1.Imdb([Movie1, Movie2]);
//console.log(imdb1.toprintf());
imdb1.escribirEnFicheroJSON("movil1");
