import{movie}from "./clase_Movie";
import {profesional}from  "./Clase_Profesional";
import {Imdb}from "./clase_imdb";
let profesional1:profesional=new profesional("tom",50,"masculino",65,170,"castaño","marron","economista","NO","Americana",0,"actor");
let profesional2:profesional=new profesional("the rock",53,"masculino",100,190,"calvo","marron","economista","NO","Americana",0,"actor");
let profesional3:profesional=new profesional("Dicaprio",45,"masculino",70,180,"castaño","azul","economista","NO","Americana",1,"actor");
let director1:profesional=new profesional("Quentin",60,"masculino",80,170,"calvo","marron","Director","NO","Americana",0,"director");
let  writer1:profesional=new profesional("Spielberg",65,"masculino",100,190,"calvo","marron","escritor","NO","Americana",0,"escritor");
let Movie1:movie=new movie("kill Bill3",2021,"americana","Quentin");
Movie1.actors=[profesional1,profesional2,profesional3];
Movie1.director=director1;
Movie1.writer=writer1;
Movie1.distributor="Universal";
Movie1.isMCU="NO";
Movie1.mainCharacterName="Tom";
Movie1.language="Ingles";
Movie1.producer="fox";
Movie1.plataform="amazon";
//console.log(Movie1.toprint());
let Movie2:movie=new movie("Kill Bill4",2022,"americana","Quentin");
Movie2.actors=[profesional3,profesional2,profesional1];
Movie2.director=writer1;
Movie2.writer=director1;
Movie2.distributor="Pixar";
Movie2.isMCU="Si";
Movie2.mainCharacterName="Dicaprio";
Movie2.language="Chino";
Movie2.producer="Universal";
Movie2.plataform="netflix";
let imdb1:Imdb= new Imdb([Movie1,Movie2]);
//console.log(imdb1.toprintf());
imdb1.escribirEnFicheroJSON("movil1"); 